# Generated by Django 6.0.5 on 2026-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_info_project_readme_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='api_docs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
