# Generated by Django 6.0.5 on 2026-05-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_api_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
