services:
  backend:
      build:
        context: ./services/core
        dockerfile: docker/Dockerfile
      restart: always
      command: ["/bin/sh", "docker/entrypoint.sh"]
      volumes:
        - ./services/core:/app
        - static_volume:/app/staticfiles
      ports:
        - "8000:8000"
      env_file:
        - ./services/core/env/.env
      environment:
        DJANGO_SETTINGS_MODULE: config.settings.production
        UV_LINK_MODE: copy
        UV_PROJECT_ENVIRONMENT: /opt/venv

  celery:
    build:
      context: ./services/core
      dockerfile: docker/Dockerfile
    restart: always
    command: uv run celery -A config.celery worker --loglevel=info --concurrency=4 --max-tasks-per-child=10 --max-memory-per-child=500000
    volumes:
      - ./services/core:/app
    env_file:
      - ./services/core/env/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production

  celery-beat:
    build:
      context: ./services/core
      dockerfile: docker/Dockerfile
    restart: always
    command: uv run celery -A config.celery beat --loglevel=info
    volumes:
      - ./services/core:/app
    env_file:
      - ./services/core/env/.env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - POOL_MODE=transaction
      - MAX_DB_CONNECTIONS=20
      - AUTH_TYPE=scram-sha-256
    ports:
      - "6432:5432"

  fastapi-parser:
    build:
      context: ./services/parser
      dockerfile: docker/Dockerfile
    restart: always
    container_name: pydocai-parser
    env_file:
      - ./services/core/env/.env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@pgbouncer:5432/${DB_NAME}
      INTERNAL_API_KEY: pydocai-internal-key
    ports:
      - "8002:8002"
    depends_on:
      - pgbouncer

  fastapi-ai:
    build:
      context: ./services/ai
      dockerfile: docker/Dockerfile
    restart: always
    container_name: pydocai-ai
    env_file:
      - ./services/core/env/.env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@pgbouncer:5432/${DB_NAME}
      DJANGO_INTERNAL_URL: http://backend:8000/api/internal
      INTERNAL_API_KEY: pydocai-internal-key
      EMBEDDING_MODEL: all-MiniLM-L6-v2
    volumes:
      - model_cache:/root/.cache/huggingface
    ports:
      - "8003:8003"
    depends_on:
      - pgbouncer

volumes:
  static_volume:
  model_cache:
