import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { getPublicProjects } from '../api'
import { IconSearch, IconGlobe, IconUser, IconClock, IconBook } from '../components/Icons'
import Navbar from '../components/Navbar'

export default function Published() {
  const navigate = useNavigate()
  const [projects, setProjects] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)
  const [search, setSearch] = useState('')
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)
  const [totalPages, setTotalPages] = useState(1)

  useEffect(() => {
    const fetchProjects = async () => {
      setLoading(true)
      setError(null)
      try {
        const res = await getPublicProjects({ page })
        const data = res.data
        setProjects(data.results ?? (Array.isArray(data) ? data : []))
        setTotal(data.count ?? 0)
        setTotalPages(data.count ? Math.ceil(data.count / 12) : 1)
      } catch {
        setError('Failed to load published projects.')
      } finally {
        setLoading(false)
      }
    }
    fetchProjects()
  }, [page])

  const filtered = projects.filter(p => {
    if (!search.trim()) return true
    const q = search.toLowerCase()
    return (p.name || '').toLowerCase().includes(q) ||
           (p.description || '').toLowerCase().includes(q)
  })

  const formatDate = (dateStr) => {
    if (!dateStr) return ''
    return new Date(dateStr).toLocaleDateString(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    })
  }

  return (
    <div className="min-h-screen bg-bg-primary flex flex-col">
      <Navbar />
      <div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-6 sm:py-8 flex-1 w-full">
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-9 sm:w-10 h-9 sm:h-10 rounded-xl bg-accent-blue/10 border border-accent-blue/20 flex items-center justify-center text-accent-blue shrink-0">
              <IconGlobe className="w-4 sm:w-5 h-4 sm:h-5" />
            </div>
            <div>
              <h1 className="text-xl sm:text-2xl font-display font-bold text-ink-primary">Published Documentation</h1>
              <p className="text-xs sm:text-sm text-ink-secondary">Browse documentation generated by the community</p>
            </div>
          </div>
        </div>

        <div className="relative mb-6">
          <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-muted">
            <IconSearch className="w-4 h-4" />
          </span>
          <input
            type="text"
            placeholder="Search projects..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="input-field pl-10 pr-4 py-2.5 text-sm w-full"
          />
          <span className="absolute right-3.5 top-1/2 -translate-y-1/2 text-[10px] font-mono text-ink-muted">
            {total} total
          </span>
        </div>

        {loading ? (
          <div className="text-center py-20 text-ink-muted">Loading...</div>
        ) : error ? (
          <div className="text-center py-20 text-danger">{error}</div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-20 text-ink-muted">
            {search ? 'No projects match your search.' : 'No published projects yet.'}
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {filtered.map((project) => (
                <div
                  key={project.id}
                  onClick={() => navigate(`/public/${project.public_slug}`)}
                  className="bg-bg-surface border border-border rounded-xl p-4 sm:p-6 hover:border-accent-blue/50 transition-colors cursor-pointer flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <IconBook className="w-4 h-4 text-accent-blue shrink-0" />
                      <h3 className="font-display font-semibold text-accent-blue truncate">
                        {project.name}
                      </h3>
                    </div>
                    <p className="text-sm text-ink-secondary line-clamp-2 mb-4">
                      {project.description || 'No description provided.'}
                    </p>
                  </div>
                  <div className="flex items-center gap-4 pt-3 border-t border-border/40 text-xs text-ink-muted">
                    <span className="flex items-center gap-1">
                      <IconUser className="w-3.5 h-3.5" />
                      {project.user_name || 'Unknown'}
                    </span>
                    <span className="flex items-center gap-1">
                      <IconBook className="w-3.5 h-3.5" />
                      {project.file_count || 0}
                    </span>
                    <span className="flex items-center gap-1 ml-auto">
                      <IconClock className="w-3.5 h-3.5" />
                      {formatDate(project.updated_at)}
                    </span>
                  </div>
                </div>
              ))}
            </div>

            {totalPages > 1 && (
              <div className="flex items-center justify-center gap-2 mt-10 pb-4 overflow-x-auto px-2">
                <button
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="px-3 py-1.5 text-xs font-mono text-ink-secondary bg-bg-surface border border-border rounded-lg hover:bg-bg-elevated disabled:opacity-30 disabled:cursor-not-allowed transition-colors shrink-0"
                >
                  Previous
                </button>
                <div className="flex items-center gap-1">
                  {Array.from({ length: totalPages }, (_, i) => i + 1).map((p) => (
                    <button
                      key={p}
                      onClick={() => setPage(p)}
                      className={`w-7 sm:w-8 h-7 sm:h-8 text-[10px] sm:text-xs font-mono rounded-lg transition-colors shrink-0 ${
                        p === page
                          ? 'bg-accent-blue text-white'
                          : 'text-ink-secondary bg-bg-surface border border-border hover:bg-bg-elevated'
                      }`}
                    >
                      {p}
                    </button>
                  ))}
                </div>
                <button
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                  className="px-3 py-1.5 text-xs font-mono text-ink-secondary bg-bg-surface border border-border rounded-lg hover:bg-bg-elevated disabled:opacity-30 disabled:cursor-not-allowed transition-colors shrink-0"
                >
                  Next
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}