# Generated by Django 5.2.13 on 2026-05-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
