# Generated by Django 5.2.13 on 2026-05-26 06:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_admin_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_replies',
                'ordering': ['created_at'],
            },
        ),
    ]
