# Generated by Django 5.2.13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_admin_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_public',
        ),
    ]
