# Generated by Django 5.2.13 on 2026-05-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_custom_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='zip_file',
        ),
    ]
