events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 ipv6=off valid=10s;

    server {
        listen 8000;
        server_name _;

        client_max_body_size 100M;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Internal-Api-Key "pydocai-internal-key";

        set $django_core "django-core:8000";
        set $fastapi_parser "fastapi-parser:8002";
        set $fastapi_ai "fastapi-ai:8003";

        location /api/users/     { proxy_pass http://$django_core; }
        location /api/projects/  { proxy_pass http://$django_core; }
        location /api/public/    { proxy_pass http://$django_core; }
        location /api/github/    { proxy_pass http://$django_core; }
        location /api/exports/   { proxy_pass http://$django_core; }
        location /api/feedback/  { proxy_pass http://$django_core; }
        location /api/admin-dashboard/ { proxy_pass http://$django_core; }
        location /api/admin/          { proxy_pass http://$django_core; }
        location /api/auth/      { proxy_pass http://$django_core; }
        location /api/parser/    { proxy_pass http://$django_core; }
        location /api/comments/  { proxy_pass http://$django_core; }
        location /api/notifications/ { proxy_pass http://$django_core; }
        location /api/ai/        { proxy_pass http://$fastapi_ai; }
        location /admin/         { proxy_pass http://$django_core; }
        location /api/universal/ { proxy_pass http://$django_core; }
        location /api/internal/  { proxy_pass http://$django_core; }
    }
}
